# -*- coding: utf-8 -*-
"""ViT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SCeKqDD79alay9Dukj3mdnPMSnbDp21C
"""

!pip install datasets

from datasets import load_dataset

data = load_dataset("blanchon/EuroSAT_RGB")

import matplotlib.pyplot as plt
import numpy as np
from torch.utils.data import DataLoader, Dataset
from torchvision import transforms
from PIL import Image
import pandas as pd
import torch
import torch.nn as nn

transform  = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5,0.5,0.5], std=[0.5,0.5,0.5]),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomVerticalFlip(p=0.5),
    transforms.RandomRotation(degrees=15),
    transforms.Resize(size=(224,224))
])

class EuroSATDataset(Dataset):
  def __init__(self, df, transform=None):
    self.df = df.reset_index(drop=True)
    self.transform = transform
  def __len__(self):
    return len(self.df)
  def __getitem__(self, idx):
    img = self.df.iloc[idx]['image']
    label = self.df.iloc[idx]['label']
    if self.transform:
      img = self.transform(img)
    return img, label

train = data['train']
validation = data['validation']

train = pd.DataFrame(train)
validation = pd.DataFrame(validation)

train_dataset = EuroSATDataset(train, transform=transform)
validation_dataset = EuroSATDataset(validation, transform=transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5,0.5,0.5], std=[0.5,0.5,0.5]),
    transforms.Resize(size=(224,224))
]))

train = train[['image','label']]
validation = validation[['image','label']]

train_loader = DataLoader(train_dataset, batch_size=128, shuffle=True)
validation_loader = DataLoader(validation_dataset, batch_size=32, shuffle=False)

import timm

model = timm.create_model('vit_small_patch16_224', pretrained=False, num_classes=10)

device = torch.device("cuda" if torch.cuda.is_available() else  "cpu")
device

criterion = nn.CrossEntropyLoss()

model.to(device)

optimizer = torch.optim.Adam(model.parameters(),lr=0.0003, weight_decay=1e-4)

history = {
    "tran_loss":[],
    "train_acc":[],
    "val_loss":[],
    "val_acc":[]
}
epochs = 100
best_val_loss = float('inf')
patience = 5
counter = 0

for epoch in range(epochs):
    model.train()
    t_loss, t_acc = 0, 0
    v_loss, v_acc = 0, 0

    for X, y in train_loader:
        X, y = X.to(device), y.to(device)
        y_pred = model(X)
        loss = criterion(y_pred, y)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        t_loss += loss.item()
        t_acc += (y_pred.argmax(dim=1)==y).sum().item()

    t_loss = t_loss / len(train_loader)
    t_acc = t_acc / len(train)
    history["tran_loss"].append(t_loss)
    history["train_acc"].append(t_acc)

    model.eval()
    with torch.inference_mode():
        for X, y in validation_loader:
            X, y = X.to(device), y.to(device)
            y_pred = model(X)
            loss = criterion(y_pred, y)
            v_loss += loss.item()
            v_acc += (y_pred.argmax(dim=1)==y).sum().item()
        v_loss = v_loss / len(validation_loader)
        v_acc = v_acc / len(validation)
        history["val_loss"].append(v_loss)
        history["val_acc"].append(v_acc)


    if v_loss < best_val_loss:
        best_val_loss = v_loss
        counter = 0
        torch.save(model.state_dict(), 'best_model.pth')
    else:
        counter += 1
        if counter >= patience:
            print(f"Early stopping at epoch {epoch+1}")
            break
    print(f"Epoch {epoch+1}/{epochs} | train_loss: {t_loss:.4f} | train_acc: {t_acc:.4f} | val_loss: {v_loss:.4f} | val_acc: {v_acc:.4f}  ")

plt.figure(figsize=(15,5))
plt.subplot(1,2,1)
plt.plot(history["tran_loss"], label="train_loss")
plt.plot(history["val_loss"], label="val_loss")
plt.legend()
plt.subplot(1,2,2)
plt.plot(history["train_acc"], label="train_acc")
plt.plot(history["val_acc"], label="val_acc")
plt.legend()
plt.show()