# -*- coding: utf-8 -*-
"""ViT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UZizPK0t4nV2PCZwJ2DN71KTC1RfitWx

## 1. 라이브러리 설치 및 임포트
"""

!pip install datasets timm -q

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

import torch
import torch.nn as nn
import timm
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms

from datasets import load_dataset

"""## 2. 데이터 로드 및 탐색"""

data = load_dataset("blanchon/EuroSAT_RGB")
print(data)

# 샘플 이미지 확인
plt.imshow(data['train'][1000]['image'])
plt.title(f"label: {data['train'][1000]['label']}")
plt.axis('off')
plt.show()

# 이미지 크기 확인
sample = np.array(data['train'][0]['image'])
print(f"이미지 shape: {sample.shape}")

"""## 3. 전처리 및 Dataset 정의"""

transform_train = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomVerticalFlip(p=0.5),
    transforms.RandomRotation(degrees=15),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
])

transform_val = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
])

class EuroSATDataset(Dataset):
    def __init__(self, df, transform=None):
        self.df = df.reset_index(drop=True)
        self.transform = transform

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        img = self.df.iloc[idx]['image']
        label = self.df.iloc[idx]['label']
        if self.transform:
            img = self.transform(img)
        return img, label

# DataFrame 변환 및 컬럼 정리
train = pd.DataFrame(data['train'])[['image', 'label']]
validation = pd.DataFrame(data['validation'])[['image', 'label']]

print(f"Train: {len(train)}개 | Validation: {len(validation)}개")
print(f"클래스: {train['label'].unique()}")

train_dataset = EuroSATDataset(train, transform=transform_train)
validation_dataset = EuroSATDataset(validation, transform=transform_val)

train_loader = DataLoader(train_dataset, batch_size=128, shuffle=True)
validation_loader = DataLoader(validation_dataset, batch_size=128, shuffle=False)

# 배치 shape 확인
sample_batch = next(iter(train_loader))[0]
print(f"배치 shape: {sample_batch.shape}")

"""## 4. 모델 정의

timm의 `vit_small_patch16_224`를 처음부터 학습 (pretrained=False)
"""

model = timm.create_model('vit_small_patch16_224', pretrained=False, num_classes=10)

total_params = sum(p.numel() for p in model.parameters())
print(f"파라미터 수: {total_params:,}")

"""## 5. 학습 설정"""

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"device: {device}")

model = model.to(device)
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.0003, weight_decay=1e-4)

"""## 6. 학습 루프

- Early Stopping: patience=5
- Best 모델 자동 저장
"""

history = {
    "train_loss": [],
    "train_acc": [],
    "val_loss": [],
    "val_acc": []
}
epochs = 100
best_val_loss = float('inf')
patience = 5
counter = 0

for epoch in range(epochs):
    model.train()
    t_loss, t_acc = 0, 0
    v_loss, v_acc = 0, 0

    for X, y in train_loader:
        X, y = X.to(device), y.to(device)
        y_pred = model(X)
        loss = criterion(y_pred, y)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        t_loss += loss.item()
        t_acc += (y_pred.argmax(dim=1) == y).sum().item()

    t_loss = t_loss / len(train_loader)
    t_acc = t_acc / len(train)
    history["train_loss"].append(t_loss)
    history["train_acc"].append(t_acc)

    model.eval()
    with torch.inference_mode():
        for X, y in validation_loader:
            X, y = X.to(device), y.to(device)
            y_pred = model(X)
            loss = criterion(y_pred, y)
            v_loss += loss.item()
            v_acc += (y_pred.argmax(dim=1) == y).sum().item()
        v_loss = v_loss / len(validation_loader)
        v_acc = v_acc / len(validation)
        history["val_loss"].append(v_loss)
        history["val_acc"].append(v_acc)

    if v_loss < best_val_loss:
        best_val_loss = v_loss
        counter = 0
        torch.save(model.state_dict(), 'best_vit.pth')
    else:
        counter += 1
        if counter >= patience:
            print(f"Early stopping at epoch {epoch+1}")
            break

    print(f"Epoch {epoch+1}/{epochs} | train_loss: {t_loss:.4f} | train_acc: {t_acc:.4f} | val_loss: {v_loss:.4f} | val_acc: {v_acc:.4f}")

"""## 7. 학습 결과 시각화"""

plt.figure(figsize=(14, 5))

plt.subplot(1, 2, 1)
plt.plot(history["train_loss"], label="train_loss")
plt.plot(history["val_loss"], label="val_loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Loss")
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history["train_acc"], label="train_acc")
plt.plot(history["val_acc"], label="val_acc")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("Accuracy")
plt.legend()

plt.tight_layout()
plt.show()

print(f"Best val_loss: {best_val_loss:.4f}")
print(f"Best val_acc: {max(history['val_acc']):.4f}")